version: '3.3'

services:

  # Nginx
  itxq-wordpress-nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${ITXQ_WORDPRESS_NGINX_PORT}:80"
    volumes:
      - ${ITXQ_WORDPRESS_PATH}docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${ITXQ_WORDPRESS_PATH}wordpress:/www:ro
      - ${ITXQ_WORDPRESS_PATH}cache/nginx:/nginx_log:rw
    depends_on:
      - itxq-wordpress-php
    links:
      - itxq-wordpress-php

  # PHP
  itxq-wordpress-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - itxq-wordpress-mysql
      - itxq-wordpress-redis
    links:
      - itxq-wordpress-mysql
      - itxq-wordpress-redis
    volumes:
      - ${ITXQ_WORDPRESS_PATH}docker/php/fpm-start.sh:/usr/bin/fpm-start.sh:ro
      - ${ITXQ_WORDPRESS_PATH}docker/php/conf.d/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ${ITXQ_WORDPRESS_PATH}docker/supervisor/conf.d:/etc/supervisor/conf.d:ro
      - ${ITXQ_WORDPRESS_PATH}wordpress:/www:rw

  # MySQL
  itxq-wordpress-mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${ITXQ_WORDPRESS_PASSWORD}
      MYSQL_DATABASE: ${ITXQ_WORDPRESS_DATABASE}
      MYSQL_USER: ${ITXQ_WORDPRESS_USERNAME}
      MYSQL_PASSWORD: ${ITXQ_WORDPRESS_PASSWORD}
    volumes:
      - ${ITXQ_WORDPRESS_PATH}storage/mysql:/var/lib/mysql:rw
      - ${ITXQ_WORDPRESS_PATH}docker/mysql/conf.d/project.cnf:/etc/mysql/conf.d/project.cnf:ro

  # Redis
  itxq-wordpress-redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    restart: always
    command: --appendonly yes
    volumes:
      - ${ITXQ_WORDPRESS_PATH}storage/redis:/data:rw
